# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Filmes' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  pod 'Alamofire', '~> 5.0.0-rc.2'

  target 'FilmesTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'FilmesUITests' do
    # Pods for testing
  end

end
